name: Deploy to S3 Static Website

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to latest version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # Updated to avoid deprecated set-output
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Upload to S3
        run: aws s3 sync . s3://mtgithubbucket-testwebsitecicd2 --delete --exclude ".git/*" --exclude ".github/*"
